#!bin/bash
#Creditos
echo -e "\e[1;32mCREDITOS AL CREADOR...!"
echo "Created by: Pollito Dorado "
echo "Date: 06/08/2018"
echo "Telegram: t.me/Jose_Vip "
echo "Youtube: https://www.youtube.com/channel/UCBWt19pL7PfmfyT2i-ymQDA/featured?view_as=subscriber "
echo -e "\e[1;33mMensaje: \e[1;36mRecuerden: "La mayoría de los buenos programadores programan, no porque esperan que se les pague o por adulación por parte del público, sino porque es divertido programar." 
- José Pariona\e[0m"
